import { db } from '../db/db'

async function buildSetlistData(setlistId) {
  const setlist = await db.setlists.get(setlistId)
  const show = await db.shows.get(setlist.showId)
  const artist = await db.artists.get(show.artistId)
  const slSets = await db.setlistSets.where('setlistId').equals(setlistId).sortBy('position')

  const sections = []
  for (const slSet of slSets) {
    const set = await db.sets.get(slSet.setId)
    const entries = await db.setEntries.where('setId').equals(slSet.setId).sortBy('position')
    const songs = []
    for (const entry of entries) {
      const song = await db.songs.get(entry.songId)
      if (song) {
        songs.push({
          title: song.title,
          bpm: entry.bpmOverride ?? song.bpm,
          timeSigN: entry.timeSigNOverride ?? song.timeSigN,
          timeSigD: entry.timeSigDOverride ?? song.timeSigD,
          notes: entry.notesOverride ?? song.notes ?? '',
        })
      }
    }
    sections.push({ name: set?.name ?? 'Set', songs })
  }

  return { artist, show, setlist, sections }
}

function buildPrintHTML(data) {
  const { artist, show, setlist, sections } = data
  const totalSongs = sections.reduce((acc, s) => acc + s.songs.length, 0)

  let songNumber = 1
  const sectionHTML = sections.map((section) => {
    const songRows = section.songs.map((song) => {
      const num = songNumber++
      const notes = song.notes ? `   <span class="notes">${song.notes}</span>` : ''
      return `<div class="song-row">
        <span class="num">${num}.</span>
        <span class="title">${song.title}</span>
        <span class="bpm">${song.bpm} BPM</span>
        <span class="timesig">${song.timeSigN}/${song.timeSigD}</span>
        ${notes}
      </div>`
    }).join('\n')

    return `<div class="section">
      <div class="section-header">${section.name.toUpperCase()}</div>
      ${songRows}
    </div>`
  }).join('\n')

  const dateStr = show.date ? ` — ${show.date}` : ''

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${setlist.name} — ${show.name}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Courier New', monospace;
    font-size: 13px;
    line-height: 1.6;
    color: #000;
    background: #fff;
    padding: 32px;
    max-width: 680px;
    margin: 0 auto;
  }
  .header { margin-bottom: 16px; }
  .artist-name { font-size: 18px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.05em; }
  .show-info { font-size: 13px; color: #444; }
  .divider { border-top: 1px solid #000; margin: 12px 0; }
  .setlist-name { font-size: 13px; color: #666; margin-bottom: 16px; }
  .section { margin-bottom: 20px; }
  .section-header { font-weight: bold; font-size: 12px; text-transform: uppercase; letter-spacing: 0.1em; color: #333; margin-bottom: 8px; margin-top: 16px; border-bottom: 1px solid #ccc; padding-bottom: 2px; }
  .song-row { display: flex; align-items: baseline; gap: 8px; padding: 2px 0; border-bottom: 1px dotted #ddd; }
  .num { width: 24px; text-align: right; color: #888; flex-shrink: 0; }
  .title { flex: 1; font-weight: bold; }
  .bpm { width: 64px; text-align: right; color: #444; flex-shrink: 0; font-size: 12px; }
  .timesig { width: 32px; text-align: center; color: #444; flex-shrink: 0; font-size: 12px; }
  .notes { color: #666; font-style: italic; font-size: 11px; }
  .footer { margin-top: 24px; color: #aaa; font-size: 10px; text-align: right; }
  @media print {
    body { padding: 16px; font-size: 12px; }
    @page { margin: 1.5cm; }
  }
</style>
</head>
<body>
  <div class="header">
    <div class="artist-name">${artist.name}</div>
    <div class="show-info">${show.name}${dateStr}</div>
  </div>
  <div class="divider"></div>
  <div class="setlist-name">${setlist.name} &middot; ${totalSongs} songs</div>
  ${sectionHTML}
  <div class="divider"></div>
  <div class="footer">Generated by SetTempo</div>
</body>
</html>`
}

export async function exportSetlistPrint(setlistId) {
  const data = await buildSetlistData(setlistId)
  const html = buildPrintHTML(data)
  const win = window.open('', '_blank')
  win.document.write(html)
  win.document.close()
  setTimeout(() => win.print(), 300)
}

export async function exportSetlistHTML(setlistId) {
  const data = await buildSetlistData(setlistId)
  const html = buildPrintHTML(data)
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${data.setlist.name.replace(/[^a-z0-9]/gi, '-')}.html`
  a.click()
  URL.revokeObjectURL(url)
}
